backend:
  name: github
  repo: jacobdeane/blog

media_library:
  name: cloudinary
  config:
    cloud_name: jacobdeane-com
    api_key: 378696241743183

display_url: http://jacobdeane.netlify.com/

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - name: category
        label: Main Category
        widget: relation
        collection: categories
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["title"]
        default: news
        required: true
      - name: other_categories
        label: Other Categories
        widget: relation
        collection: categories
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["title"]
        multiple: true
        required: false
        hint: Only used for displaying the categories, please include the main category in this list too.
      - name: hero_image
        label: Hero Image
        widget: image
        media_library:
          config:
            multiple: false
        required: false
      - { name: dark_image, label: Dark Hero Image?, widget: boolean, hint: Toggle on if the hero image is dark, default: false, required: false }
      - { name: excerpt, label: Excerpt, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }


  - name: astrophotography
    label: Astrophotography
    label_singular: Astro Image
    folder: content/astrophotography
    create: true
    fields:
      - { name: title, label: Title }
      - name: designations
        label: Designations
        label_singular: Designation
        widget: list
        summary: '{{fields.designation}}'
        field: { label: Designation, name: designation }
        required: false
      - name: hero_image 
        label: Image
        widget: image
        media_library:
          config: 
            multiple: false
      - { name: body, label: Description, widget: markdown, required: false }
      - { name: start_date, label: Imaging Start Date, widget: date, required: false }
      - { name: end_date, label: Imaging End Date, widget: date, required: false }
      - { name: location, label: Imaging Location, required: false }
      - name: ra
        label: Right Ascension (RA)
        hint: "Format: HH MM SS.S"
        pattern: ['[0-9]{2}[ ][0-9]{2}[ ][0-9]{2}[.]*[0-9]*', "HH MM SS.S"]
        required: false
      - name: dec
        label: Declination (DEC) 
        hint: "Format: ±DD MM SS.S"
        pattern: ['[+-][0-9]{2}[ ][0-9]{2}[ ][0-9]{2}[.]*[0-9]*', "±DD MM SS.S"]
        required: false
      - { name: distance, label: Distance from Earth, hint: Light Years, widget: number, required: false }
      - { name: telescope, label: Imaging Telescope, required: false }
      - { name: camera, label: Imaging Camera, required: false }
      - { name: mount, label: Mount, required: false }
      - name: exposure_details
        label: Exposure Details
        widget: list
        summary: '{{fields.filter}}: {{fields.multiple}} x {{fields.sub}} seconds'
        fields:
          - name: filter
            label: Filter
            widget: select
            options:
              - { label: Luminance, value: Luminance }
              - { label: Red, value: R }
              - { label: Green, value: G }
              - { label: Blue, value: B }
              - { label: Hydrogen Alpha, value: Ha }
              - { label: Oxygen III, value: OIII }
              - { label: Sulpher II, value: SII }
          - name: multiple
            label: Number of sub-exposures
            widget: number
          - name: sub
            label: Length of sub-exposures (seconds)
            widget: number
            hint: seconds
  
  - name: categories
    label: Categories
    label_singular: Category
    folder: content/categories
    create: true
    fields:
      - { name: title, label: Category }
