backend:
#  name: github
#  repo: jacobdeane/blog
  name: proxy
  proxy_url: http://localhost:8081/api/v1

media_folder: content/assets
public_folder: ../assets

collections:
  - name: blog
    label: Blog
    label_singular: Post
    folder: content/blog
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Date, widget: date }
      - name: category
        label: Main Category
        widget: relation
        collection: categories
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["title"]
        default: news
        required: true
      - name: other_categories
        label: Other Categories
        widget: relation
        collection: categories
        searchFields: ["title"]
        valueField: "{{slug}}"
        displayFields: ["title"]
        multiple: true
        required: false
      - name: hero_image
        label: Hero Image
        widget: image
        media_library:
          config:
            multiple: false
        required: false
      - { name: dark_image, label: Dark Hero Image?, widget: boolean, hint: Toggle on if the hero image is dark, default: false, required: false }
      - { name: excerpt, label: Excerpt, widget: text, required: false }
      - { name: body, label: Body, widget: markdown }

  - name: pages
    label: Pages
    label_singular: Page
    folder: content/pages
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }


  - name: astrophotography
    label: Astrophotography
    label_singular: Astro Image
    folder: content/astrophotography
    create: true
    media_folder: /content/assets/astro
    public_folder: ../assets/astro
    fields:
      - { name: title, label: Title }
      - name: image 
        label: Image
        widget: image
        required: false
        media_library:
          config: 
            multiple: false
      - { name: start_date, label: Imaging Start Date, widget: date, required: false }
      - { name: end_date, label: Imaging End Date, widget: date, required: false }
      - { name: location, label: Imaging Location, required: false }
      - name: ra
        label: Right Ascension (RA)
        hint: "Format: HH MM SS.S"
        pattern: ['[0-9]{2}[ ][0-9]{2}[ ][0-9]{2}[.]*[0-9]*', "HH MM SS.S"]
        required: false
      - name: dec
        label: Declination (DEC) 
        hint: "Format: ±DD MM SS.S"
        pattern: ['[+-][0-9]{2}[ ][0-9]{2}[ ][0-9]{2}[.]*[0-9]*', "±DD MM SS.S"]
        required: false
      - { name: distance, label: Distance from Earth, hint: Light Years, widget: number, required: false }
      - { name: description, label: Description, widget: markdown, required: false }
  
  - name: categories
    label: Categories
    label_singular: Category
    folder: content/categories
    create: true
    fields:
      - { name: title, label: Category }
